export const ActionTypes = {
    // GET_CURRENT_USER: "GET_CURRENT_USER",
    // FETCH_CLASSES: "FETCH_CLASSES",
    // SET_CLASSES: "SET_CLASSES",
    // SELECTED_CLASS: "SELECTED_CLASS",
    // REMOVE_SELECTED_CLASS: "REMOVE_SELECTED_CLASS",

    GET_CLASS_MEMBERS_LIST: "GET_CLASS_MEMBERS_LIST",
};