export const ActionTypes = {
  // GET_CURRENT_USER: "GET_CURRENT_USER",
  // FETCH_CLASSES: "FETCH_CLASSES",
  // SET_CLASSES: "SET_CLASSES",
  // SELECTED_CLASS: "SELECTED_CLASS",
  // REMOVE_SELECTED_CLASS: "REMOVE_SELECTED_CLASS",

  GET_CLASS_MEMBERS_LIST: "GET_CLASS_MEMBERS_LIST",
  ADD_CLASS_MEMEBERS: "ADD_CLASS_MEMEBER",
  GET_CLASS_DETAILS: "GET_CLASS_DETAILS",
  RESET_SELECTED_CLASS: "RESET_SELECTED_CLASS",
  
  GET_SELECTED_CLASS_MODULES: "GET_SELECTED_CLASS_MODULES",
  GET_MODULE_DETAILS:"GET_MODULE_DETAILS",
  RESET_SELECTED_CLASS_MODULES: "RESET_SELECTED_CLASS_MODULES",

  GET_SELECTED_MODULE_POSTS:"GET_SELECTED_MODULE_POSTS",
  GET_POST_DETAILS:"GET_POST_DETAILS",
  RESET_SELECTED_MODULE_POSTS: "RESET_SELECTED_MODULE_POSTS",
  RESET_POST_DETAILS:"RESET_POST_DETAILS",

  GET_PARENT_COMMENTS:"GET_PARENT_COMMENTS",
  RESET_PARENT_COMMENTS:"RESET_PARENT_COMMENTS",
  GET_CHILDREN_COMMENTS:"GET_CHILDREN_COMMENTS",
  RESET_CHILDREN_COMMENTS:"RESET_CHILDREN_COMMENTS",

  SEND_PARENT_REPLY:"SEND_PARENT_REPLY",
  SEND_CHILD_REPLY:"SEND_CHILD_REPLY",

  GET_ALL_USERS:"GET_ALL_USERS",
  GET_SINGLE_USER:"GET_SINGLE_USER",
  RESET_SINGLE_USER:"RESET_SINGLE_USER",
  RESET_ALL_USERS:"RESET_ALL_USERS",

  GET_QUIZ_LISTS:"GET_QUIZ_LISTS",
  GET_QUIZ_DETAILS:"GET_QUIZ_DETAILS",
  RESET_SELECTED_CLASS_QUIZ:"RESET_SELECTED_CLASS_QUIZ",
  RESET_QUIZ_DETAILS:"RESET_QUIZ_DETAILS",

  GET_RANDOM_SCQ_QUESTIONS:"GET_RANDOM_SCQ_QUESTIONS",
  RESET_RANDOM_SCQ_QUESTIONS:"RESET_RANDOM_SCQ_QUESTIONS",
  GET_RANDOM_BQ_QUESTIONS:"GET_RANDOM_BQ_QUESTIONS",
  GET_RANDOM_THEORY_QUESTIONS:"GET_RANDOM_THEORY_QUESTIONS",

  GET_NO_RECORD:"GET_NO_RECORD",
};
